# Configuração do Codecov para commit-wizard
# https://docs.codecov.io/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 5%

# Analytics e Relatórios
analytics:
  enabled: true
  track_coverage_trends: true
  track_file_coverage: true
  track_branch_coverage: true
  track_function_coverage: true

# Configurações de Parser
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

# Comentários em PRs
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  show_cov_project_labels: true
  show_cov_patch_labels: true

# Configurações de Ignore
ignore:
  - "tests/"
  - "**/*.test.ts"
  - "**/*.test.js"
  - "**/__tests__/"
  - "bin/"
  - "dist/"
  - "scripts/"
  - "examples/"
  - "docs_ai/"
  - ".github/"
  - "*.config.js"
  - "*.config.ts"
  - "bunfig.toml"
  - "tsconfig.json"
  - "package.json"
  - "README.md"
  - "LICENSE"
  - "SECURITY.md"
  - "CONTRIBUTING.md"

# GitHub Checks
github_checks:
  annotations: true
  wait_for_ci: true

# Flags para diferentes tipos de teste
flags:
  unittests:
    paths:
      - "src/"
    carryforward: true
  integration:
    paths:
      - "tests/integration.test.ts"
      - "tests/smart-split.test.ts"
    carryforward: true

# Configurações de API
api:
  version: v2
  timeout: 30
  retries: 3

# Notificações
notifications:
  slack:
    url: $CODECOV_SLACK_WEBHOOK
    channel: "#coverage"
    on_success: change
    on_failure: change
  webhook:
    url: $CODECOV_WEBHOOK_URL
    on_success: change
    on_failure: change

# Configurações de Cache
cache:
  enabled: true
  ttl: 3600
  max_size: 100

# Configurações de Segurança
security:
  require_auth: true
  allow_anonymous: false 